version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    environment:
      PORT: "8080"
      BUCKET_NAME: goout-bucket
      GOOGLE_APPLICATION_CREDENTIALS: /credentials/web-gcloud-account.json
    ports:
      - "8080:8080"
    volumes:
      - "./credentials:/credentials:ro"
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    environment:
      PORT: "8081"
    ports:
      - "8081:8081"
