version: "3.7"
services:
  backend:
    build: .
    environment:
      PORT: "8080"
      GOOGLE_APPLICATION_CREDENTIALS: /credentials/gcloud-storage-account.json
    ports:
      - "8080:8080"
    volumes:
      - "./credentials:/credentials"
