apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: web-service
spec:
  template:
    spec:
      containers:
        - image: gcr.io/kupcimat/web
          env:
            - name: BUCKET_NAME
              value: goout-bucket
      serviceAccountName: kupcimat-web@kupcimat.iam.gserviceaccount.com
